### ISSUE TITLE
Multiple ssh keys?

### ISSUE THREAD

**Issue by MIJOTHY** [buildkite/elastic-ci-stack-s3-secrets-hooks#29]
Does this currently support importing multiple ssh keys?

**Comment by keithduncan** [comment]
The current version of this plug-in does [fetch](https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/blob/71e04a450068de7ca7d64500b34995f8fa9c3b9e/s3secrets-helper/secrets/secrets.go#L95-L107) multiple S3 keys and those present are loaded into the `ssh-agent`:

![Screenshot 2021-07-09 at 15 33 01](https://user-images.githubusercontent.com/22101/125028328-2c3b5180-e0cb-11eb-8e87-2e44abf65303.png)

This is largely a side effect of supporting multiple key names in the S3 storage layer and supporting separate pipeline / global keys. Multiple SSH keys can cause issues with providers like GitHub who use SSH for _authentication_ and accept the first known key without considering _authorization_. A git fetch authenticated over SSH may fail if the key that was accepted doesn’t have permission, despite having an agent with multiple keys loaded.

If your use case is to use the SSH agent in your Buildkite Job to connect disparate hosts that will accept different keys from the agent, you may be better served with a different plug-in that specifically loads a list of referenced keys into the agent.

I hope that is helpful, please let me know if I can provide more detail on anything above 😄
