### ISSUE TITLE
503 error when trying to download secrets file

### ISSUE THREAD

**Issue by jonasxiv** [buildkite/elastic-ci-stack-s3-secrets-hooks#51]
I've been having a lot of errors that break the builds when the agents try to downloads the secrets file from the secrets bucket:
```
fatal error: ServiceUnavailable: Service Unavailable
--
  | status code: 503, request id: 8EZA6SF5B53WDWRP, host id:
```

After retrial it usually works

**Comment by keithduncan** [comment]
Sorry you’ve run into this @jonasxiv, how often is this occurring in your builds?

**Comment by bruno** [comment]
We have been seeing the same behaviour, I think I've traced it back to this specific call https://github.com/buildkite/elastic-ci-stack-s3-secrets-hooks/blob/922b375a124b6620bdac362341b107dc56bdb8f8/s3secrets-helper/s3/s3.go#L44 ... I am not 100% sure, could it be that we're hitting some sort of rate limit and AWS is returning that 503? (seeing this from the docs of the `type Error` at https://pkg.go.dev/github.com/aws/aws-sdk-go/service/s3):

```
	//    * Code: ServiceUnavailable Description: Reduce your request rate. HTTP
	//    Status Code: 503 Service Unavailable SOAP Fault Code Prefix: Server
```
