### ISSUE TITLE
setting AWS_PROFILE in a build step causes s3-secrets failure

### ISSUE THREAD

**Issue by jeremiahsnapp** [buildkite/elastic-ci-stack-s3-secrets-hooks#9]
If I set the AWS_PROFILE environment variable on a build step the s3-secrets plugin's aws-cli commands fail if that profile hasn't already been setup in `~/.aws/credentials`.

The failure is occurring here.

https://github.com/buildkite-plugins/s3-secrets-buildkite-plugin/blob/master/lib/shared.bash#L8

I was easily able to reproduce this by logging into a buildkite instance as the buildkite-agent user and running the following command.

```
$ AWS_PROFILE="some-profile" aws s3api head-object --region=us-east-1 --bucket secrets --key private_ssh_key
Traceback (most recent call last):
  File "/usr/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/usr/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 58, in main
    rc = driver.main()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 193, in main
    command_table = self._get_command_table()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 102, in _get_command_table
    self._command_table = self._build_command_table()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 122, in _build_command_table
    command_object=self)
  File "/usr/lib/python2.7/dist-packages/botocore/session.py", line 719, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/dist-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 317, in service_model
    return self._get_service_model()
  File "/usr/lib/python2.7/dist-packages/awscli/clidriver.py", line 334, in _get_service_model
    api_version = self.session.get_config_variable('api_versions').get(
  File "/usr/lib/python2.7/dist-packages/botocore/session.py", line 279, in get_config_variable
    elif self._found_in_config_file(methods, var_config):
  File "/usr/lib/python2.7/dist-packages/botocore/session.py", line 306, in _found_in_config_file
    return var_config[0] in self.get_scoped_config()
  File "/usr/lib/python2.7/dist-packages/botocore/session.py", line 383, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile () could not be found
```

Here is the successful run when AWS_PROFILE isn't set.

```
$ aws s3api head-object --region=us-east-1 --bucket secrets --key private_ssh_key
{
    "AcceptRanges": "bytes",
    "ContentType": "text/plain",
    "LastModified": "Wed, 14 Feb 2018 23:12:20 GMT",
    "ContentLength": 3243,
    "VersionId": "8zNleT1gVCq10Wxrcgd3DSccPo7BO2d2",
    "ETag": "\"1828798ae87a3dbc4dbd6ef7ff5f9d28\"",
    "Metadata": {}
}
```

I'm able to workaround this but is there anything that can be done within this plugin to make it easier for users?

**Comment by lox** [comment]
Hmmm, that's a tricky one! Presumably you are setting `AWS_PROFILE` in an environment hook or similar? It being set in a build step shouldn't impact the plugin.

**Comment by jeremiahsnapp** [comment]
No, I'm really just setting it in the build step like this.

```
  - label: simple demo
    command: echo "hello world"
    env:
      AWS_PROFILE: bogus-profile
```

You can see that the first which uploads the pipeline yaml successfully downloads the s3 secrets.

<img width="603" alt="screen shot 2018-03-09 at 9 21 00 am" src="https://user-images.githubusercontent.com/430911/37211922-822ac41a-237b-11e8-847e-837c4d4976ad.png">

You can also see here that its environment doesn't include the `AWS_PROFILE`. This is all normal behavior.

<img width="427" alt="screen shot 2018-03-09 at 9 21 51 am" src="https://user-images.githubusercontent.com/430911/37212042-eea098d6-237b-11e8-98cf-83785a10416b.png">

But here's the `simple demo` step. It fails to find any secrets in the s3 bucket.

<img width="1164" alt="screen shot 2018-03-09 at 9 21 23 am" src="https://user-images.githubusercontent.com/430911/37212069-fd43bab2-237b-11e8-8676-1e61fe02366e.png">

And you can see that `AWS_PROFILE` is included in this step's environment because that's how I defined the step.

<img width="439" alt="screen shot 2018-03-09 at 9 21 35 am" src="https://user-images.githubusercontent.com/430911/37212105-1e2998a0-237c-11e8-9bf6-90a103aed7ec.png">


As I described in my original post the failure is occurring here because the `aws s3api head-object` command is being run with `AWS_PROFILE` set to a profile that hasn't yet been configured in `~/.aws/credentials`.

https://github.com/buildkite-plugins/s3-secrets-buildkite-plugin/blob/master/lib/shared.bash#L8

I'm not sure of the best solution but perhaps it's possible for the s3-secrets plugin to unset `AWS_PROFILE`? But we would want to make sure that `AWS_PROFILE` is still correctly set after the s3-secrets plugin runs so the rest of the step works as expected.

**Comment by lox** [comment]
Sorry for the slow response, spent some time thinking over what the correct API boundary was for these. I think you're correct and that we shouldn't be loading in credentials or config from ENV outside of what is configured for the plugin.

**Comment by keithduncan** [comment]
I’ve just tested this with the latest build of the secrets hook and a job environment `AWS_PROFILE` doesn’t interfere with the s3 secrets fetch any more :tada:

This was likely fixed with v2 of this plug-in and v5 of the Elastic CI Stack that uses it:

![Screenshot 2021-07-09 at 15 17 10](https://user-images.githubusercontent.com/22101/125026975-dbc2f480-e0c8-11eb-88d0-af1e6eca72a4.png)

![Screenshot 2021-07-09 at 15 17 16](https://user-images.githubusercontent.com/22101/125026982-dd8cb800-e0c8-11eb-8d13-dbba8706ce3d.png)

Let us know if you’re still running into this with an updated stack and we can take another look 🙇‍♂️
